#!/bin/bash
# Manual test for cross-file hover with master file
# This script demonstrates how to test the fix manually

echo "=========================================="
echo "Manual Test: Cross-File Hover"
echo "=========================================="
echo ""
echo "This test verifies that hover works on variables defined in required files"
echo "when a master file is set."
echo ""
echo "Test Files:"
echo "  - test/fixtures/transitive/top.jazz (master file)"
echo "  - test/fixtures/transitive/middle.jinc (required by top.jazz)"
echo "  - test/fixtures/transitive/base.jinc (required by middle.jinc)"
echo ""
echo "Steps to test:"
echo "1. Build the LSP server: dune build"
echo "2. Start VS Code extension in debug mode (F5)"
echo "3. Open test/fixtures/transitive/ as workspace"
echo "4. Set master file to top.jazz using the command:"
echo "   - Cmd+Shift+P → 'Jasmin: Set Master File' → top.jazz"
echo "5. Open top.jazz and hover over 'BASE_CONSTANT' on line 9"
echo "   Expected: Shows 'param BASE_CONSTANT: int = 42'"
echo "6. Open middle.jinc and hover over 'base_function' on line 7"
echo "   Expected: Shows 'fn base_function(reg u64 x) -> reg u64'"
echo ""
echo "Expected Results:"
echo "✓ Hover on symbols defined in directly required files works"
echo "✓ Hover on symbols defined in transitively required files works"
echo "✓ Constant values are computed and displayed"
echo ""
echo "Key Changes Made:"
echo "1. LspProtocol.ml: Modified receive_text_document_hover_request"
echo "   - Now builds complete source_map upfront with all files from master file"
echo "   - Uses pre-built source_map for all symbol lookups"
echo "   - Ensures constant values are resolved from all files in dependency tree"
echo ""
echo "2. How it works:"
echo "   - get_all_relevant_files() collects all files reachable from master file"
echo "   - build_source_map() loads and parses all files once"
echo "   - enhance_constants_with_values() uses complete source_map for evaluation"
echo "   - Symbol search uses the pre-built source_map instead of loading files individually"
echo ""
