[project]
name = "jasmin-lsp"
version = "0.0.1"
description = "Jasmin Language Server Protocol (LSP) implementation"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
gmp = "*"
mpfr = "*"
pkgconf = "*"
ppl = "*"
tree-sitter-cli = "0.25.*"
libtree-sitter = "0.25.*"
clang = "*"

[activation.env]
C_INCLUDE_PATH = "$CONDA_PREFIX/include"
CPLUS_INCLUDE_PATH = "$CONDA_PREFIX/include"
LIBRARY_PATH = "$CONDA_PREFIX/lib"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig"
CFLAGS = "-I$CONDA_PREFIX/include"
LDFLAGS = "-L$CONDA_PREFIX/lib"

[tasks]
build-tree-sitter = "cd tree-sitter-jasmin && make clean && make"
clean = "dune clean"
build = { cmd = "dune build", depends-on = ["build-tree-sitter"] }
test = { cmd = "dune test", depends-on = ["build"] }
run = { cmd = "_build/default/jasmin-lsp/jasmin_lsp.exe", depends-on = ["build"] }
install-opam = "opam install . --assume-depexts --working-dir"
setup = { depends-on = ["build-tree-sitter", "install-opam"] }