name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'jasmin-lsp/**'
      - 'tree-sitter-jasmin/**'
      - 'test/**'
      - 'dune-project'
      - 'jasmin-lsp.opam'
      - 'pixi.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'jasmin-lsp/**'
      - 'tree-sitter-jasmin/**'
      - 'test/**'
      - 'dune-project'
      - 'jasmin-lsp.opam'
      - 'pixi.toml'
      - '.github/workflows/ci.yml'

env:
  OCAML_VERSION: "5.3.0"

jobs:
  build-and-test:
    name: Build and Test on Linux AMD64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ env.OCAML_VERSION }}
          dune-cache: true
          opam-disable-sandboxing: true
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgmp-dev \
            libmpfr-dev \
            libppl-dev \
            pkg-config
      
      - name: Install tree-sitter library
        run: |
          # Install libtree-sitter from source (version 0.25.x)
          wget https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.25.3.tar.gz
          tar -xzf v0.25.3.tar.gz
          cd tree-sitter-0.25.3
          make
          sudo make install
          sudo ldconfig
      
      - name: Install Python and pytest
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-timeout pytest-cov pytest-xdist pytest-sugar pytest-html
      
      - name: Cache opam dependencies
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: opam-${{ runner.os }}-${{ env.OCAML_VERSION }}-${{ hashFiles('jasmin-lsp.opam', 'dune-project') }}
          restore-keys: |
            opam-${{ runner.os }}-${{ env.OCAML_VERSION }}-
      
      - name: Pin jasmin to working version
        run: |
          opam pin add jasmin 2025.04.0 --no-action -y
      
      - name: Install OCaml dependencies
        run: |
          opam install . --deps-only --assume-depexts
      
      - name: Build tree-sitter-jasmin
        run: |
          cd tree-sitter-jasmin
          make clean
          make
          ls -lh libtree-sitter-jasmin.so || ls -lh libtree-sitter-jasmin.a
      
      - name: Build jasmin-lsp
        run: |
          eval $(opam env)
          dune build
          ls -lh _build/default/jasmin-lsp/jasmin_lsp.exe
      
      - name: Run tests
        run: |
          eval $(opam env)
          pytest test -v --timeout=30 --tb=short
        env:
          C_INCLUDE_PATH: /usr/local/include
          LIBRARY_PATH: /usr/local/lib
          LD_LIBRARY_PATH: /usr/local/lib
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.xml
            htmlcov/
          retention-days: 7
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jasmin-lsp-linux-amd64
          path: _build/default/jasmin-lsp/jasmin_lsp.exe
          retention-days: 30
